import { FormEvent, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";
import "./phase2.css";
import "./phase3.css";

type User = { id: string; email: string };
type Config = { configured?: boolean; base_url?: string; api_key_set?: boolean; model?: string };
type Project = { id: string; name: string; last_accessed_at: string };
const api = async <T,>(path: string, init?: RequestInit): Promise<T> => {
  const response = await fetch(`/api${path}`, { credentials: "include", headers: { "Content-Type": "application/json", ...(init?.headers || {}) }, ...init });
  if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.error || "REQUEST_FAILED"); }
  if (response.status === 204) return undefined as T;
  return response.json();
};

function Auth({ onUser }: { onUser: (user: User) => void }) {
  const [registering, setRegistering] = useState(false); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); try { onUser(await api<User>(`/auth/${registering ? "register" : "login"}`, { method: "POST", body: JSON.stringify({ email, password }) })); } catch (e) { setError(e instanceof Error ? e.message : "Unable to continue"); } }
  return <main className="auth"><section className="auth-card"><p className="eyebrow">ATOMS</p><h1>{registering ? "Create your account" : "Welcome back"}</h1><p className="muted">Build small web apps through a simple conversation.</p><form onSubmit={submit}><label>Email<input autoComplete="email" type="email" required value={email} onChange={e=>setEmail(e.target.value)} /></label><label>Password<input autoComplete={registering ? "new-password" : "current-password"} type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)} /></label>{error && <p className="error">{error.replaceAll("_", " ")}</p>}<button>{registering ? "Register" : "Sign in"}</button></form><button className="text-button" onClick={()=>setRegistering(!registering)}>{registering ? "Already have an account? Sign in" : "New here? Create an account"}</button></section></main>;
}

function Navigation({ page, setPage, user, logout }: { page:string; setPage:(p:string)=>void; user:User; logout:()=>void }) { return <aside><div className="brand">atoms</div><nav>{["home","projects","settings"].map(item=><button key={item} className={page===item ? "active" : ""} onClick={()=>setPage(item)}>{item[0].toUpperCase()+item.slice(1)}</button>)}</nav><div className="account"><span>{user.email}</span><button onClick={logout}>Sign out</button></div></aside>; }

function Home({ setPage, project, onCreated }: {setPage:(p:string)=>void; project:Project|null; onCreated:(p:Project)=>void}) { const [request,setRequest]=useState("");const [error,setError]=useState(""); async function build(){if(project){setPage("project");return}setError("");try{const r=await api<{project:Project}>("/project",{method:"POST",body:JSON.stringify({name:request.trim()||"Untitled project"})});onCreated(r.project);setPage("project")}catch(e){setError(e instanceof Error?e.message:"Unable to create project")}}return <section className="page home"><div className="hero"><p className="eyebrow">YOUR NEXT APP</p><h1>{project?"Continue your project":"What do you want to build?"}</h1><p className="muted">{project?`Your current project is ${project.name}. Runtime and preview are ready.`:"Describe a focused web app to create its isolated environment."}</p><textarea aria-label="Describe your app" value={request} onChange={e=>setRequest(e.target.value)} placeholder={project?"Open the workspace to request changes.":"Describe your app..."} disabled={!!project}/>{error&&<p className="error">{error.replaceAll("_"," ")}</p>}<button onClick={build}>{project?"Open project →":"Create project →"}</button><p className="hint">{project?"Request changes and review them in the live preview.":<>Configure your model service in <button className="link" onClick={()=>setPage("settings")}>Settings</button> before requesting implementation.</>}</p></div></section> }
function Projects({setPage,project}:{setPage:(p:string)=>void;project:Project|null}) { return <section className="page"><p className="eyebrow">WORKSPACE</p><h1>Projects</h1>{project?<div className="project-card"><div><h2>{project.name}</h2><p>One project is supported in P0. Runtime is isolated and restored on access.</p></div><button onClick={()=>setPage("project")}>Open →</button></div>:<div className="empty"><h2>No project yet</h2><p>Start by describing what you want to build from Home.</p><button onClick={()=>setPage("home")}>Go to Home</button></div>}</section> }
function ProjectWorkspace({project}:{project:Project}) { const [status,setStatus]=useState("Restoring project environment…"),[reload,setReload]=useState(0),[messages,setMessages]=useState<{id:string;role:string;content:string}[]>([]),[text,setText]=useState(""),[run,setRun]=useState<string|null>(null),[inspect,setInspect]=useState(false),[selected,setSelected]=useState<unknown>(null),[token,setToken]=useState("");const load=()=>api<{messages:{id:string;role:string;content:string}[]}>("/project/messages").then(r=>setMessages(r.messages));useEffect(()=>{const h=(e:MessageEvent)=>{if(e.data?.type==="atoms-selected-ui"){setSelected(e.data.selected_ui);setInspect(false)}};window.addEventListener("message",h);return()=>window.removeEventListener("message",h)},[]);useEffect(()=>{api<{preview_token:string}>("/project/preview-access").then(r=>setToken(r.preview_token)).catch(()=>undefined)},[]);useEffect(()=>{load();api<{exists:boolean;running:boolean}>("/project/runtime/status").then(s=>setStatus(s.running?"Runtime running":"Runtime is starting")).catch(()=>setStatus("Runtime unavailable"))},[reload]);useEffect(()=>{if(!run)return;const e=new EventSource(`/api/project/runs/${run}/events`);e.addEventListener("status",v=>{const x=JSON.parse((v as MessageEvent).data);setStatus(x.status);if(["COMPLETED","FAILED","CANCELLED"].includes(x.status)){e.close();setRun(null);load();setReload(n=>n+1)}});return()=>e.close()},[run]);async function send(){if(!text.trim()||run)return;const r=await api<{run_id:string}>("/project/messages",{method:"POST",body:JSON.stringify({content:text,selected_ui:selected})});setText("");setSelected(null);load();setRun(r.run_id)}const preview=`http://p-${project.id}.localhost:8080/?preview_token=${token}&preview=${reload}`;return <section className="workspace"><header><div><p className="eyebrow">PROJECT WORKSPACE</p><h1>{project.name}</h1></div><span className="runtime">● {status}</span></header><div className="workspace-body"><aside className="chat"><div className="history">{messages.map(m=><p key={m.id} className={m.role}>{m.content}</p>)}</div>{Boolean(selected)&&<p className="muted">Selected UI ready</p>}{run&&<p className="muted">{status} <button className="link" onClick={()=>api(`/project/runs/${run}/cancel`,{method:"POST"})}>Cancel</button></p>}<textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Ask for a change…"/><button onClick={send} disabled={!!run}>Send</button></aside><div className="preview"><div className="preview-bar"><strong>Preview</strong><button className="secondary" onClick={()=>setReload(v=>v+1)}>Refresh</button><button className="secondary" onClick={()=>{setInspect(v=>!v);document.querySelector<HTMLIFrameElement>('iframe[title="Project preview"]')?.contentWindow?.postMessage({type:"atoms-inspect",enabled:!inspect},"*")}}>Inspect UI</button></div>{token?<iframe key={reload} title="Project preview" src={preview}/>:<p className="muted">Loading preview…</p>}</div></div></section> }
function Settings() { const [config,setConfig]=useState<Config>({});const [base_url,setBaseURL]=useState("");const [api_key,setKey]=useState("");const [model,setModel]=useState("");const [message,setMessage]=useState("");
 useEffect(()=>{api<Config>("/llm-config").then(c=>{setConfig(c);setBaseURL(c.base_url||"");setModel(c.model||"");}).catch(()=>undefined)},[]);
 const payload=()=>({base_url,api_key,model}); async function save(){setMessage("");try{await api("/llm-config",{method:"PUT",body:JSON.stringify(payload())});setKey("");setConfig({configured:true,base_url,model,api_key_set:true});setMessage("Saved.")}catch(e){setMessage(e instanceof Error?e.message:"Unable to save")}} async function test(){setMessage("Testing connection…");try{const r=await api<{message:string}>("/llm-config/test",{method:"POST",body:JSON.stringify(api_key?payload():{base_url:"",api_key:"",model:""})});setMessage(r.message)}catch{setMessage("The configured model service is unavailable or not compatible with the required Responses API.")}}
 return <section className="page settings"><p className="eyebrow">SETTINGS</p><h1>Model Service</h1><p className="muted">Current model service must be compatible with the OpenAI Responses API.</p><label>Base URL<input value={base_url} onChange={e=>setBaseURL(e.target.value)} placeholder="https://api.example.com/v1" /></label><label>API Key<input value={api_key} onChange={e=>setKey(e.target.value)} type="password" placeholder={config.api_key_set ? "Saved key — enter a new value to replace" : "API key"} /></label><label>Model<input value={model} onChange={e=>setModel(e.target.value)} placeholder="model-name" /></label>{message&&<p className={message==="Connection successful"||message==="Saved."?"success":"error"}>{message}</p>}<div className="actions"><button className="secondary" onClick={test}>Test Connection</button><button onClick={save}>Save</button></div></section> }
function App(){const [user,setUser]=useState<User|null>(null);const [page,setPage]=useState("home");const [project,setProject]=useState<Project|null>(null);useEffect(()=>{api<User>("/me").then(setUser).catch(()=>undefined)},[]);useEffect(()=>{if(user)api<{project:Project|null}>("/project").then(r=>setProject(r.project)).catch(()=>undefined)},[user]);if(!user)return <Auth onUser={setUser}/>;return <div className="shell"><Navigation page={page} setPage={setPage} user={user} logout={async()=>{await api("/auth/logout",{method:"POST"});setUser(null);setProject(null)}}/><main>{page==="home"&&<Home setPage={setPage} project={project} onCreated={setProject}/>} {page==="projects"&&<Projects setPage={setPage} project={project}/>} {page==="settings"&&<Settings/>} {page==="project"&&project&&<ProjectWorkspace project={project}/>}</main></div>};
createRoot(document.getElementById("root")!).render(<App/>);
